packer {
  required_version = ">= 1.0.0"
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

variable "aws_instance" {
  type    = string
  default = "t3.small"
}

variable "aws_region" {
  type    = string
  default = "us-east-2"
}

variable "infra_env" {
  type    = string
  default = ""
}

variable "infra_name" {
  type    = string
  default = "erpnext"
}

data "amazon-ami" "autogenerated" {
  filters = {
    architecture        = "x86_64"
    name                = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"] # Canonical
  profile     = "erpnext"
  region      = "${var.aws_region}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated" {
  ami_name      = "${var.infra_name}-${var.infra_env}-${local.timestamp}-app"
  instance_type = "${var.aws_instance}"
  launch_block_device_mappings {
    delete_on_termination = true
    device_name           = "/dev/sda1"
    encrypted             = false
    iops                  = 3000
    throughput            = 125
    volume_size           = 8
    volume_type           = "gp3"
  }
  profile      = "erpnext"
  region       = "${var.aws_region}"
  source_ami   = "${data.amazon-ami.autogenerated.id}"
  ssh_username = "ubuntu"
  tags = {
    Component   = "app"
    Environment = "${var.infra_env}"
    ManagedBy   = "packer"
    Name        = "${var.infra_name}-${var.infra_env}-${local.timestamp}-app"
    Project     = "${var.infra_name}"
    Role        = "baked-ami"
    Unique      = "baked-ami-${local.timestamp}"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]

  provisioner "ansible" {
    extra_arguments = []
    playbook_file   = "playbooks/erpnext.yml"
    roles_path      = [
      
    ]
  }
}
